const board = [
  [
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' } 
  ],
  [
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' }
   ],
   [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
  ],
  [ 
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' } 
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' }
  ],
  [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'DL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' }
   ],
   [ 
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TL' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: 'TW' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' },
      { val: ' ', bonus: '' } 
    ]
];